version: '3.7'
services:
  react-app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    environment:
      - REACT_APP_NAME=Arif hossain
      - CHOKIDAR_POLLING=true
    # env_file:
    #   - ./.env.local
